name: Check for dist file changes

# From https://github.com/github/docs/blob/main/.github/workflows/triage-unallowed-contributions.yml

on:
  pull_request_target:
    paths:
      - "dist/**"

permissions:
  pull-requests: write

jobs:
  triage:
    if: >-
      ${{
        github.event.pull_request.user.login != 'semantic-release-bot'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Get files changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          # Base branch used to get changed files
          base: "main"

          # Enables setting an output in the format in `${FILTER_NAME}_files
          # with the names of the matching files formatted as JSON array
          list-files: json

          # Returns list of changed files matching each filter
          filters: |
            notAllowed:
              - 'dist/**'

      # When there are changes to files we can't accept, leave a comment
      # explaining this to the PR author
      - name: "Comment about changes we can't accept"
        if: ${{ steps.filter.outputs.notAllowed }}
        uses: actions/github-script@v6
        with:
          script: |
            let reviewMessage = `👋 Hey there. It looks like you've modified some of the `dist` files.\nYou'll need to revert all of the changes that you've made to these files. Once you get those files reverted, we can continue with the review process. :octocat:`
            let workflowFailMessage = "It looks like you've modified some of the `dist` files."

            try {
              createdComment = await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                body: reviewMessage,
              })

              workflowFailMessage = `${workflowFailMessage} Please see ${createdComment.data.html_url} for details.`
            } catch(err) {
              console.log("Error creating comment.", err)
            }

            core.setFailed(workflowFailMessage)
